### ISSUE TITLE
1.0 Release Checklist

### ISSUE THREAD

**Issue by JamesRamm** [JamesRamm/longclaw#99]
Checklist for 1.0 release:

- [x] Wagtail/Django 2
- [x] Update changelist
- [x] Updated docs / website
- [x] Deploy website to GH pages
- [ ] Update longclaw demo to longclaw 'bakery'
- [ ] Deploy longclaw bakery (heroku?)
- [x] Review documentation
- [x] Tag master
- [x] Push to pypi
- [ ] Announcements

**Comment by JamesRamm** [comment]
This issue is just to keep track of the menial tasks for the release (and highlight the fact that we are nearing release!)

**Comment by JamesRamm** [comment]
Closing this - longclaw demo support will be tracked in its own repo
